services:
  sipexer:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SIPEXER_TAG: ${SIPEXER_TAG:-main}
    container_name: sipexer
    restart: "on-failure"
    networks:
      common-network:
        ipv4_address: 172.25.0.20  # Assign a specific IP
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    stdin_open: true
    privileged: true
    tty: true

networks:
  common-network:
    external: true
